export const ProductData = [
  {
    id: 1,
    name: 'Expresso Tradicional',
    description: 'O tradicional café feito com água quente e grãos moídos',
    price: 9.9,
    type: 'Tradicional',
    url: 'public/coffees/expresso-tradicional.svg',
    quantity: 1,
  },
  {
    id: 2,
    name: 'Expresso Americano',
    description: 'Expresso diluído, menos intenso que o tradicional',
    price: 9.9,
    type: 'Tradicional',
    url: 'public/coffees/expresso-americano.svg',
    quantity: 1,
  },
  {
    id: 3,
    name: 'Expresso Cremoso',
    description: 'Café expresso tradicional com espuma cremosa',
    price: 9.9,
    type: 'Tradicional',
    url: 'public/coffees/expresso-cremoso.svg',
    quantity: 1,
  },
  {
    id: 4,
    name: 'Expresso Gelado',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 9.9,
    type: 'Tradicional',
    url: 'public/coffees/expresso-gelado.svg',
    quantity: 1,
  },
  {
    id: 5,
    name: 'Latte',
    description: 'Café expresso com o dobro de leite e espuma cremosa',
    price: 9.9,
    type: 'Tradicional',
    url: 'public/coffees/latte.svg',
    quantity: 1,
  },
  {
    id: 6,
    name: 'Café com Leite',
    description: 'Bebida preparada com café expresso e cubos de gelo',
    price: 9.9,
    type: 'Tradicional',
    url: 'public/coffees/cafe-com-leite.svg',
    quantity: 1,
  },
  {
    id: 7,
    name: 'Capuccino',
    description: 'Bebida com canela feita de doses de café, leite e espuma',
    price: 9.9,
    type: 'Doce',
    url: 'public/coffees/capuccino.svg',
    quantity: 1,
  },
  {
    id: 8,
    name: 'Macchiato',
    description:
      'Café expresso misturado com um pouco de leite quente e espuma',
    price: 9.9,
    type: 'Doce',
    url: 'public/coffees/macchiato.svg',
    quantity: 1,
  },
  {
    id: 9,
    name: 'Mocaccino',
    description: 'Café expresso com calda de chocolate, pouco leite e espuma',
    price: 9.9,
    type: 'Doce',
    url: 'public/coffees/mocaccino.svg',
    quantity: 1,
  },
  {
    id: 10,
    name: 'Chocolate Quente',
    description: 'Bebida feita com chocolate dissolvido no leite quente e café',
    price: 9.9,
    type: 'Doce',
    url: 'public/coffees/chocolate-quente.svg',
    quantity: 1,
  },
  {
    id: 11,
    name: 'Cubano',
    description:
      'Drink gelado de café expresso com rum, creme de leite e hortelã',
    price: 9.9,
    type: 'Especial',
    url: 'public/coffees/cafe-cubano.svg',
    quantity: 1,
  },
  {
    id: 12,
    name: 'Havaiano',
    description: 'Bebida adocicada preparada com café e leite de coco',
    price: 9.9,
    type: 'Especial',
    url: 'public/coffees/cafe-havaiano.svg',
    quantity: 1,
  },
  {
    id: 13,
    name: 'Árabe',
    description: 'Bebida preparada com grãos de café árabe e especiarias',
    price: 9.9,
    type: 'Especial',
    url: 'public/coffees/cafe-arabe.svg',
    quantity: 1,
  },
  {
    id: 14,
    name: 'Irlandês',
    description: 'Bebida a base de café, uísque irlandês, açúcar e chantilly',
    price: 9.9,
    type: 'Especial',
    url: 'public/coffees/cafe-irlandes.svg',
    quantity: 1,
  },
]
